export const products = [
  {
    id: 1,
    sku: 'DVD123',
    name: 'Awesome DVD',
    description: 'An amazing DVD for your entertainment',
    price: 19.99,
    type_id: 1,
    type_specific_value: '120',
  },
  {
    id: 2,
    sku: 'BOOK456',
    name: 'Bestseller Book',
    description: 'A top-rated book that you must read',
    price: 29.99,
    type_id: 2,
    type_specific_value: '1.5',
  },
  {
    id: 3,
    sku: 'FURN789',
    name: 'Elegant Furniture',
    description: 'High-quality furniture for your home',
    price: 199.99,
    type_id: 3,
    type_specific_value: '120x80x180',
  },
  {
    id: 4,
    sku: 'DVD456',
    name: 'Fantastic DVD',
    description: 'A fantastic DVD with great content',
    price: 24.99,
    type_id: 1,
    type_specific_value: '90',
  },
  {
    id: 5,
    sku: 'BOOK789',
    name: 'Classic Novel',
    description: 'A classic novel that you will love',
    price: 39.99,
    type_id: 2,
    type_specific_value: '2.0',
  },
  {
    id: 6,
    sku: 'FURN123',
    name: 'Modern Furniture Set',
    description: 'Modern furniture set for contemporary living',
    price: 299.99,
    type_id: 3,
    type_specific_value: '150x90x200',
  },
  {
    id: 7,
    sku: 'DVD789',
    name: 'Superior DVD Collection',
    description: 'A collection of superior quality DVDs',
    price: 29.99,
    type_id: 1,
    type_specific_value: '110',
  },
  {
    id: 8,
    sku: 'BOOK123',
    name: 'Educational Book',
    description: 'An educational book for learning purposes',
    price: 19.99,
    type_id: 2,
    type_specific_value: '1.2',
  },
  {
    id: 9,
    sku: 'FURN456',
    name: 'Vintage Furniture Piece',
    description: 'A vintage furniture piece with timeless design',
    price: 249.99,
    type_id: 3,
    type_specific_value: '100x70x150',
  },
  {
    id: 10,
    sku: 'DVD456',
    name: 'Action-Packed DVD Set',
    description: 'A set of action-packed DVDs for entertainment',
    price: 34.99,
    type_id: 1,
    type_specific_value: '95',
  },
];
